# Generated by Django 4.1.3 on 2022-11-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='course',
            new_name='availability',
        ),
    ]
